### ISSUE TITLE
Generate script to create attendee guide from coach guide

### ISSUE THREAD

**Issue by Bertg** [brug-be/railsgirls_guide#2]
The attendee guide should basically be an HTML page, excluding the `coach_info` blocks from the main `CoachGuide.md` file.

**Comment by wrtsprt** [comment]
Currently we only have one of those blocks, which are on a page we should burry somewhere or even remove (since it's confusing - see https://github.com/railsgirls-be/railsgirls_guide/issues/21). 

Is that issue currently still relevant?

**Comment by wrtsprt** [comment]
@bert ping?

**Comment by borisrorsvort** [comment]
@wrtsprt @Bertg  I believe the extra info about the schedule should not be there as it is present in http://railsgirls.com/brussels and all the communication that goes with it. It makes it harder to update it if something changes as you have to update it everywhere

**Comment by Bertg** [comment]
Let's remove it the :)
